// SOC2-style evidence pack builder.
//
// Procurement reality: every enterprise security questionnaire ends with
// "please share evidence that controls X, Y, Z are operating effectively".
// This module produces a single deterministic .zip an admin can hand to
// their auditor (or attach to a vendor questionnaire) without us writing
// a bespoke PDF report each cycle.
//
// What's inside:
//   README.md                       — index + how to interpret each file
//   manifest.json                   — generation metadata + sha256 of each
//                                     file in the pack
//   controls-inventory.json         — every enterprise control, status,
//                                     and the route that owns it
//   policies/                       — current value of every workspace
//                                     policy (SSO, network, CORS, CSP,
//                                     retention, rotation, egress, ...)
//   audit-chain-verification.json   — tamper-evident chain replay result
//   keys.json                       — every API key, scopes/role/revoked
//                                     flag, ip allowlist (no secrets)
//   sessions.json                   — active SSO sessions snapshot
//
// Determinism: every file is JSON.stringify'd with 2-space indent and
// sorted top-level keys. The pack always includes a `generated_at` field
// (non-deterministic by design), so an auditor can prove they're holding
// the pack issued for a specific date. SHA-256 hashes in manifest.json
// let the auditor verify the bundle was not edited after handoff.
//
// Auth: callers must already be admin-gated. This builder does not
// re-check auth; it just gathers data the caller has been authorized to
// read.

import { createHash } from "node:crypto";
import { Buffer } from "node:buffer";
import { buildAdminIndex } from "./adminIndex.ts";
import { verifyChain } from "./auditStore.ts";
import { listKeys, publicView as keyPublicView } from "./keyStore.ts";
import { listSessions } from "./ssoSessionRegistry.ts";
import { getSsoPolicy } from "./ssoPolicyStore.ts";
import { getPolicy as getNetworkPolicy } from "./networkPolicyStore.ts";
import { getPolicy as getCorsPolicy } from "./corsPolicy.ts";
import { getCspPolicy } from "./cspPolicyStore.ts";
import { getPolicy as getRetentionPolicy } from "./retentionStore.ts";
import { getRotationPolicy } from "./rotationPolicy.ts";
import { getPolicy as getEgressPolicy } from "./egressPolicy.ts";
import { getResidencyPolicy } from "./residencyStore.ts";
import { getConfig as getLockoutConfig } from "./authLockoutStore.ts";
import { getConcurrencyPolicy } from "./concurrencyStore.ts";
import { getSettings } from "./settingsStore.ts";
import { listHolds } from "./legalHoldStore.ts";
import { getSink as getSiemSink } from "./siemSinkStore.ts";
import { getFreezeState } from "./freezeStore.ts";
import { buildZip, type ZipEntry } from "./zipBuilder.ts";

function stableJson(value: unknown): string {
  return JSON.stringify(sortKeys(value), null, 2) + "\n";
}

function sortKeys(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sortKeys);
  if (value && typeof value === "object") {
    const out: Record<string, unknown> = {};
    for (const k of Object.keys(value as Record<string, unknown>).sort()) {
      out[k] = sortKeys((value as Record<string, unknown>)[k]);
    }
    return out;
  }
  return value;
}

function sha256Hex(buf: Buffer): string {
  return createHash("sha256").update(buf).digest("hex");
}

function safeCall<T>(fn: () => T | Promise<T>): Promise<T | null> {
  try {
    return Promise.resolve(fn()).catch(() => null);
  } catch {
    return Promise.resolve(null);
  }
}

// Redacts an SSO session record so the pack never carries a usable token.
// We keep email, role, ip_hash, timing, and revocation reason because
// those are what an auditor inspecting "who was logged in when X
// happened" actually wants.
function redactSession(r: any) {
  return {
    sid: r.sid,
    email: r.email,
    role: r.role,
    iat: r.iat,
    exp: r.exp,
    last_seen: r.last_seen ?? null,
    ip_hash: r.ip_hash ?? null,
    user_agent: r.user_agent ?? null,
    revoked_at: r.revoked_at ?? null,
    revoked_reason: r.revoked_reason ?? null,
  };
}

const README = `# SignalClaw SOC2 evidence pack

This archive is a point-in-time snapshot of the security controls
configured in this SignalClaw workspace. It is generated by an
admin-authenticated, audit-logged call to \`/api/admin/evidence-pack\`
and is intended to be handed to an external auditor or attached to a
vendor security questionnaire.

## Contents

- \`manifest.json\` — generation metadata and a SHA-256 of every file in
  this archive. If any file is edited after handoff the hash will not
  match and the pack should be treated as untrusted.
- \`controls-inventory.json\` — the full enterprise control inventory
  with on/off/enforcing status and the admin surface that owns each.
- \`policies/\` — current value of each workspace-level policy (SSO,
  network allowlist, CORS, CSP, retention, rotation, webhook egress,
  data residency, lockout, concurrency, freeze, SIEM, holds, defaults).
- \`audit-chain-verification.json\` — result of replaying the
  tamper-evident audit chain on disk; \`ok: true\` proves no audit
  record has been modified or removed.
- \`keys.json\` — every API key in the workspace with role, scopes,
  revoked / suspended / expired flags, and per-key IP allowlist. No
  secret material is included.
- \`sessions.json\` — currently active SSO sessions with timing,
  hashed IP, and user agent. No session tokens.

## Verifying the pack

\`\`\`
unzip evidence-pack.zip -d pack/
cd pack
jq -r '.files[] | "\\(.sha256)  \\(.name)"' manifest.json | shasum -a 256 -c
\`\`\`

Every line should print \`OK\`. If any line fails the archive was
modified after the workspace signed it.
`;

export type EvidencePack = {
  buffer: Buffer;
  filename: string;
  generated_at: string;
};

export async function buildEvidencePack(actorId: string | null = null): Promise<EvidencePack> {
  const generated_at = new Date().toISOString();

  const [
    controls,
    chain,
    keys,
    sessionsResp,
    sso,
    network,
    cors,
    csp,
    retention,
    rotation,
    egress,
    residency,
    lockout,
    concurrency,
    settings,
    holds,
    siem,
    freeze,
  ] = await Promise.all([
    safeCall(() => buildAdminIndex()),
    safeCall(() => verifyChain()),
    safeCall(() => listKeys()),
    safeCall(() => listSessions({ include_revoked: false, limit: 500 })),
    safeCall(() => getSsoPolicy()),
    safeCall(() => getNetworkPolicy()),
    safeCall(() => getCorsPolicy()),
    safeCall(() => getCspPolicy()),
    safeCall(() => getRetentionPolicy()),
    safeCall(() => getRotationPolicy()),
    safeCall(() => getEgressPolicy()),
    safeCall(() => getResidencyPolicy()),
    safeCall(() => getLockoutConfig()),
    safeCall(() => getConcurrencyPolicy()),
    safeCall(() => getSettings()),
    safeCall(() => listHolds()),
    safeCall(() => getSiemSink()),
    safeCall(() => getFreezeState()),
  ]);

  const keysPublic = (keys ?? []).map(keyPublicView);
  const sessionsPublic = (sessionsResp?.sessions ?? []).map(redactSession);

  const files: { name: string; body: string }[] = [
    { name: "README.md", body: README },
    { name: "controls-inventory.json", body: stableJson(controls) },
    { name: "audit-chain-verification.json", body: stableJson(chain) },
    { name: "keys.json", body: stableJson({ count: keysPublic.length, keys: keysPublic }) },
    {
      name: "sessions.json",
      body: stableJson({
        active_count: sessionsResp?.active_count ?? 0,
        global_epoch: sessionsResp?.global_epoch ?? 0,
        sessions: sessionsPublic,
      }),
    },
    { name: "policies/sso.json", body: stableJson(sso) },
    { name: "policies/network.json", body: stableJson(network) },
    { name: "policies/cors.json", body: stableJson(cors) },
    { name: "policies/csp.json", body: stableJson(csp) },
    { name: "policies/retention.json", body: stableJson(retention) },
    { name: "policies/rotation.json", body: stableJson(rotation) },
    { name: "policies/webhook-egress.json", body: stableJson(egress) },
    { name: "policies/residency.json", body: stableJson(residency) },
    { name: "policies/auth-lockout.json", body: stableJson(lockout) },
    { name: "policies/concurrency.json", body: stableJson(concurrency) },
    { name: "policies/workspace-defaults.json", body: stableJson(settings) },
    { name: "policies/legal-holds.json", body: stableJson({ count: (holds ?? []).length, holds: holds ?? [] }) },
    { name: "policies/siem-sink.json", body: stableJson(siem) },
    { name: "policies/freeze.json", body: stableJson(freeze) },
  ];

  // Manifest is computed AFTER every other file body is finalized so it
  // can hash the on-disk bytes exactly. It is intentionally the last
  // file added to the zip so its own hash is not part of the hashing.
  const fileBuffers = files.map((f) => ({ name: f.name, buf: Buffer.from(f.body, "utf8") }));
  const manifest = {
    generated_at,
    generated_by: actorId,
    product: "signalclaw",
    pack_version: "1",
    files: fileBuffers
      .map((f) => ({ name: f.name, size: f.buf.length, sha256: sha256Hex(f.buf) }))
      .sort((a, b) => a.name.localeCompare(b.name)),
  };
  const manifestBuf = Buffer.from(stableJson(manifest), "utf8");

  const entries: ZipEntry[] = [
    ...fileBuffers.map((f) => ({ name: f.name, data: f.buf })),
    { name: "manifest.json", data: manifestBuf },
  ];

  return {
    buffer: buildZip(entries),
    filename: `signalclaw-evidence-${generated_at.slice(0, 10)}.zip`,
    generated_at,
  };
}
